//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eims.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EimsContext : DbContext
    {
        public EimsContext()
            : base("name=con")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Suggest> Suggest { get; set; }
        public virtual DbSet<Wage> Wage { get; set; }
    }
}
